#!/bin/bash
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH -t 00:40:00
#SBATCH -o train.output
#SBATCH -e train.error

module load python/2.7.11
module load cuda/7.5.18
module load cudnn/7.5-v5

srun -u python retrain_vgg.py --learning_rate 0.00001 --refine_after_k 1000 --max_steps 7000 --checkpoint_dir ./checkpoints/vgg_cnn_refine1000_lrl2 --log_dir ./logs/cifar10/vgg_cnn_refine1000_lrl2 --print_freq 100 --eval_freq 100 --checkpoint_freq 5000